# -*- coding: utf-8 -*-
"""Magic Number Spell Practice

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sJYDRSJjBaVypl_6gFIjG6l0BwOCLFFY
"""

'''
In the land of wizards, there is an old spell that says that every magic number must have a special property:

If a number is divisible by 3, it is considered a magic number.

If a number is divisible by 5, it is considered a cursed number.

If a number is both magic and cursed, it is considered a legendary number.

Otherwise, it is a regular number.

Your task: Write a program that takes an integer as input and determines whether it is a magic, cursed, legendary, or regular number.

Make sure that the words in quotation marks are displayed exactly as the output.

Input:

An integer n

Output:

If n is divisible by 3, print: "magical"

If n is divisible by 5, print: "cursed"

If n is divisible by both, print: "legendary"

Otherwise, print: "ordinary"

Sample input 1:

9

Sample output 1:

magical

Sample input 2:

10

Sample output 2:

cursed
'''
# Read an integer from the user
n = int(input())

# Check the magical conditions
if n % 3 == 0 and n % 5 == 0:
    print("Legendary")
elif n % 3 == 0:
    print("Magic")
elif n % 5 == 0:
    print("cursed")
else:
    print("regular")