# -*- coding: utf-8 -*-
"""Magic Machine

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sJYDRSJjBaVypl_6gFIjG6l0BwOCLFFY
"""

'''
We have a machine called the “magic machine” that takes a prime number n and wants to get to 1. The machine can do two things:

If the current number is divisible by 2, it halve it.

If the current number is not divisible by 2, it multiplies the number by 3 and adds 1 to it.

Your task is to write a program that takes the prime number n as input and show how the machine gets to 1.

Input:

An integer n (2 ≤ n ≤ 1000)

Output:

At each step, print the current value of n until the number reaches 1.

Sample Input:

50

Sample Output:

50
25
76
38
19
58
29
88
44
22
11
34
17
52
26
13
40
20
10
5
16
8
4
2
1
'''
# Read the initial number from the user
n = int(input())

# Repeat the process until n becomes 1
while True:
    print(n)  # Print the current value of n
    if n == 1:
        break
    elif n % 2 == 0:
        n = n // 2
    else:
        n = n * 3 + 1