# -*- coding: utf-8 -*-
"""Ring Magic

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sJYDRSJjBaVypl_6gFIjG6l0BwOCLFFY
"""

'''

A wizard has decided to increase the power of numbers using a special spell! He chooses a number n and then does the following for n steps:

If the number is odd, he doubles its value and subtracts 1 unit.

If the number is even, he halves its value.

The wizard performs this operation exactly n times.
📝 Input:

An integer n that specifies the number of steps (1 ≤ n ≤ 20).
An integer x that is the initial value (1 ≤ x ≤ 1000).
📤 Output:

Finally, display the final value of x.
Input 1:

5
10

Output 1:

65
'''
# Read input values
n = int(input())  # number of steps
x = int(input())  # initial value

# Perform the operation n times
for _ in range(n):
    if x % 2 == 0:
        x = x // 2
    else:
        x = x * 2 - 1

# Output the final value
print(x)