# -*- coding: utf-8 -*-
"""Even or Odd Exercise

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sJYDRSJjBaVypl_6gFIjG6l0BwOCLFFY
"""

'''
In this exercise, you need to define a function called is_even that checks whether a given number is even or odd. This is a fundamental concept in mathematics and programming that is used in many problems.

Your task:
Define a function called is_even(n) that:

Takes an integer n as input.

Checks whether the number is even or not.

Returns True if the number is even.

Returns False if the number is odd.
The value should be returned, not printed directly.
Inputs:
An integer n read from the input.
Outputs:
A True value if the number is even.
A False value if the number is odd.

Sample Input 1:

8

Expected Output 1:

True

Sample Input 2:

15

Expected Output 2:

False
'''
def is_even(n):
    return n % 2 == 0
print(is_even(8))   # Output: True
print(is_even(15))  # Output: False