# -*- coding: utf-8 -*-
"""Greater or Less Exercise

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sJYDRSJjBaVypl_6gFIjG6l0BwOCLFFY
"""

'''
In this exercise, you need to define a function called is_greater(a, b) that checks whether a is greater than b.

Your task:
Define a function called is_greater(a, b) that:

Takes two integers a and b as input.

Checks whether a is greater than b.

Returns True if a > b.

Returns False if a ≤ b.

The value should be returned and not printed directly.
Inputs:
Two integers a and b read from the input.
Outputs:
A True value if a is greater than b.

A False value if a is less than or equal to b.

Sample Input 1:

10

5

Expected Output 1:

True

Sample Input 2:

3
7

Expected Output 2:

False
'''

def is_greater(a, b):
    return a > b

print(is_greater(10, 5))  # Output: True
print(is_greater(3, 7))   # Output: False