# -*- coding: utf-8 -*-
"""Hello name

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sJYDRSJjBaVypl_6gFIjG6l0BwOCLFFY
"""

'''
Write a function called greet that takes a name as input and prints "Hello, Name!"
 (The value of the input should be displayed instead of Name.)

Sample input:

Ali

Expected output:

Hello, Ali!
'''
def greet(name):
    print(f"Hello, {name}!")
greet("Ali")