# -*- coding: utf-8 -*-
"""Input from args Exercise

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sJYDRSJjBaVypl_6gFIjG6l0BwOCLFFY
"""

'''
In this exercise, you need to define a function called sum_numbers(*args) that can take any number of numbers and return their sum.

Your task:
Write a function called sum_numbers(*args) that: Takes an unlimited number of numbers as input.
Computes and returns the sum of these numbers.
If no numbers are passed, returns 0.

Inputs:
Zero or more integers that are passed to the sum_numbers function.

Outputs:
A number that represents the sum of all inputs.
If no inputs are passed, returns 0.

Input and output examples:
Sample input 1:

5 10 15

Expected output 1:

30

Sample input 2:

7 3 2 1 9

Expected output 2:

22

Because 7 + 3 + 2 + 1 + 9 = 22
'''

def sum_numbers(*args):
    return sum(args)

print(sum_numbers(5, 10, 15))        # Output: 30
print(sum_numbers(7, 3, 2, 1, 9))    # Output: 22
print(sum_numbers())                # Output: 0