# -*- coding: utf-8 -*-
"""Pick Evens Exercise

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sJYDRSJjBaVypl_6gFIjG6l0BwOCLFFY
"""

'''
In this exercise, you need to write a function called pick_evens(*args) that takes a series of numbers and returns only even numbers.

Your task:
Write a function called pick_evens(*args) that: Takes an unlimited number of numbers as input.
Returns only even numbers as a list.
If there are no even numbers, return an empty list [].

Inputs:
Multiple integers that are passed to the pick_evens function.

Outputs:
A list containing only even numbers.
If there are no even numbers in the input, return an empty list [].

Sample Input 1:

1 2 3 4 5 6

Expected Output 1:

[2, 4, 6]

Because only even numbers remain in the list.

Sample Input 2:

7 13 19 21

Expected Output 2:

[]

Because there are no even numbers.
'''

def pick_evens(*args):
    return [num for num in args if num % 2 == 0]

print(pick_evens(1, 2, 3, 4, 5, 6))     # Output: [2, 4, 6]
print(pick_evens(7, 13, 19, 21))        # Output: []
print(pick_evens())                     # Output: []