# -*- coding: utf-8 -*-
"""Sum of Squares Exercise

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sJYDRSJjBaVypl_6gFIjG6l0BwOCLFFY
"""

'''
In this exercise, you need to write a function that takes two integers and calculates the sum of their squares.

Your task:
Write a function called sum_of_squares that takes two integers and returns the sum of the squares of those two numbers.

Calculation formula:

sum_of_squares(a,b)=a**2+b**2

Inputs:
Two integers (int).

Outputs:
An integer that is the sum of the squares of the two input numbers.

Sample Input 1:

3
4
Expected Output 1:

25

(Because 32+42=9+16=25)

Sample Input 2:

5
12

Expected Output 2:

169

(Because 52+122=25+144=169)
'''
def sum_of_squares(a, b):
    return a**2 + b**2
print(sum_of_squares(3, 4))   # Output: 25
print(sum_of_squares(5, 12))  # Output: 169